# Generated by Django 5.2.17 on 2026-09-28 15:57

import apps.service_requests.models
import apps.service_requests.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.service_requests.models.attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.service_requests.validators.validate_attachment_size]),
        ),
    ]
